# Generated by Django 3.2.25 on 2025-12-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('BiletID', models.IntegerField(db_column='BiletID', primary_key=True, serialize=False)),
                ('SatisZaani', models.DateTimeField(db_column='SatisZamani')),
            ],
            options={
                'db_table': 'Bilet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('FilmID', models.IntegerField(db_column='FilmID', primary_key=True, serialize=False)),
                ('Ad', models.CharField(db_column='Ad', max_length=100)),
                ('Tur', models.CharField(db_column='Tur', max_length=50)),
                ('Sure', models.IntegerField(db_column='Sure')),
                ('Aciklama', models.TextField(db_column='Aciklama', null=True)),
                ('VizyonTarihi', models.DateField(db_column='VizyonTarihi')),
            ],
            options={
                'db_table': 'Film',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Koltuk',
            fields=[
                ('KoltukID', models.IntegerField(db_column='KoltukID', primary_key=True, serialize=False)),
                ('Sira', models.CharField(db_column='Sira', max_length=2)),
                ('Numara', models.IntegerField(db_column='Numara')),
            ],
            options={
                'db_table': 'Koltuk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('KullaniciID', models.IntegerField(db_column='KullaniciID', primary_key=True, serialize=False)),
                ('Ad', models.CharField(db_column='Ad', max_length=50)),
                ('Soyad', models.CharField(db_column='Soyad', max_length=50)),
                ('Eposta', models.CharField(db_column='Eposta', max_length=100)),
                ('Rol', models.CharField(db_column='Rol', max_length=10)),
            ],
            options={
                'db_table': 'Kullanici',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('SalonID', models.IntegerField(db_column='SalonID', primary_key=True, serialize=False)),
                ('Ad', models.CharField(db_column='Ad', max_length=50)),
                ('Kapasite', models.IntegerField(db_column='Kapasite')),
            ],
            options={
                'db_table': 'Salon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('SeansID', models.IntegerField(db_column='SeansID', primary_key=True, serialize=False)),
                ('Tarih', models.DateField(db_column='Tarih')),
                ('Saat', models.TimeField(db_column='Saat')),
                ('Fiyat', models.DecimalField(db_column='Fiyat', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'Seans',
                'managed': False,
            },
        ),
    ]
